# docker-compose.local.yml
services:
  # Backend - Express API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: taskmaster-backend-dev
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=1d
      - JWT_REFRESH_EXPIRATION=7d
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
      - ENABLE_NOTIFICATIONS=true
      - ENABLE_WEBSOCKETS=true
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    command: >
      sh -c "
        npx prisma generate &&
        npm run dev
      "

  # Frontend - React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: taskmaster-frontend-dev
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:4000/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
    command: >
      sh -c "
        npm run dev -- --host
      "
