version: '3.8'

services:
  # Traefik - Reverse Proxy
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config:/etc/traefik
    networks:
      - web
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=${CLOUDFLARE_EMAIL}"
      - "--certificatesresolvers.cloudflare.acme.storage=/etc/traefik/acme.json"
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}

  # Frontend - React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmaster-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # Configuración HTTPS
      - "traefik.http.routers.taskmaster-secure.rule=Host(`taskmaster.urbanlink.pe`)"
      - "traefik.http.routers.taskmaster-secure.entrypoints=websecure"
      - "traefik.http.routers.taskmaster-secure.tls=true"
      - "traefik.http.routers.taskmaster-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.taskmaster-secure.service=taskmaster"
      # Configuración HTTP sin redirección
      - "traefik.http.routers.taskmaster.rule=Host(`taskmaster.urbanlink.pe`)"
      - "traefik.http.routers.taskmaster.entrypoints=web"
      - "traefik.http.routers.taskmaster.service=taskmaster"
      # Configuración del servicio
      - "traefik.http.services.taskmaster.loadbalancer.server.port=80"

  # Backend - Express API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmaster-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - CORS_ORIGIN=https://taskmaster.urbanlink.pe
      - ENABLE_NOTIFICATIONS=true
      - ENABLE_WEBSOCKETS=true
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # Configuración HTTPS
      - "traefik.http.routers.api-taskmaster-secure.rule=Host(`api.taskmaster.urbanlink.pe`)"
      - "traefik.http.routers.api-taskmaster-secure.entrypoints=websecure"
      - "traefik.http.routers.api-taskmaster-secure.tls=true"
      - "traefik.http.routers.api-taskmaster-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.api-taskmaster-secure.service=api-taskmaster"
      # Configuración HTTP sin redirección
      - "traefik.http.routers.api-taskmaster.rule=Host(`api.taskmaster.urbanlink.pe`)"
      - "traefik.http.routers.api-taskmaster.entrypoints=web"
      - "traefik.http.routers.api-taskmaster.service=api-taskmaster"
      # Configuración del servicio
      - "traefik.http.services.api-taskmaster.loadbalancer.server.port=4000"

networks:
  web:
    external: true
